language:
  - bash

services:
  - docker

sudo: true

jobs:
  include:
    - stage: build
      script: ./ci/bin/docker_build_and_push.sh 0.4.0/alpine bats:0.4.0 bats:0.4.0-alpine bats:0.4.0-rc2
    - stage: build
      script: ./ci/bin/docker_build_and_push.sh 1.1.0/debian bats bats:1.1.0 bats:1.1.0-debian

